---
# tasks file for 01-update-linux-software
- name: Apt Update 
  ansible.builtin.apt:
    update_cache: true

- name: Apt upgrade
  ansible.builtin.apt:
    upgrade: yes 

- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: yes

- name: Run the equivalent of "apt-get clean" as a separate step
  ansible.builtin.apt:
    clean: yes