---
- name: Setup Dockered DBs and Queque server
  hosts: dbs
  become: false
  roles:
    - {role: 00-ping, when: ansible_system == "Linux"}
    - {role: 05-setup-dbs, when: ansible_system == "Linux"}
